### ISSUE TITLE
Unable to create external tags

### ISSUE THREAD

**Issue by mikes222** [ergonlabs/liquid_dart#6]
I wanted to implement the `regroup` tag in my project since it is missing in the builtin tags. Unfortunately I am not able to create tags in my project because a couple of classes are not exposed. These are: `Expression`, `Tag`, `Token`, `TagParser`, `TokenType`, `Parser`, `ParseException`. 
There may be other necessary classes but for my first try that's it. Please make them available. 
Regards, 
Mike

**Comment by rdmorris** [comment]
Hey Mike,
A short term solution is to override the existing dependency.
```
dependencies:
  liquid_engine: ^0.1.2
  ...
  
dependency_overrides:
  liquid_engine:
    path: /path/to/your/liquid_engine
  ...
```
